services:
  gen_data:
    build: .
    command: sh -c "mkdir -p output && ./gen_data 10 10 5"    #m, n, k
    volumes:
      - ./output:/app/output

  p2:
    build: .
    command: ./p2 3 5 # num_queries, k
    networks:
      - mpc_net
    depends_on:
      - gen_data

  p0:
    build: .
    command: ./p0 10 10 5 3   # m, n, k, number of queries # Sir, please change the values accordingly, this program can be used for any value under 2^16 as you specified in the class
    networks:
      - mpc_net
    depends_on:
      - p2

  p1:
    build: .
    command: ./p1 10 10 5 3
    networks:
      - mpc_net
    depends_on:
      - p2

networks:
  mpc_net: